[package]
name = "osm-render-nav"
version = "0.1.0"
authors = ["Bjorn Martens <bjorn@expeditious.nl>"]
edition = "2018"

[dependencies]
winit = "0.24"
wgpu = "0.7"
glsl-to-spirv = "0.1.7"
bytemuck = "1.5.0"
futures = "0.3"
lyon = "0.17"
osmpbf = "0.2"
